## numpy 2D array 

In [1]:
import numpy as np 
a =  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b = np.array(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### np 0s and 1s

In [ ]:
import numpy as np 
a=np.zeros(10,dtype=int)
for i in range(0,10):
    if i==4:
        a[i]=1
    print(a[i],end=' ') 

### np inclusive

In [ ]:
import numpy as np
b = np.arange(9,50)
for i in b :
    print(i,end = " ")  

### identity matrix

In [ ]:
import numpy as np 
b = np.eye(5,6,dtype = int)
print(b)

### cut rope

In [ ]:
import numpy  as np 
d = np.linspace(0,5,9, endpoint = False)
for i in d :
    if i!=0.00 :
        format_float = "{:.2f}".format(i)
        print(format_float) 

### print elements

In [ ]:
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)

a = input_[2,0:3]
for i in a :
    print(i,end = " ")
print()

a = input_[1:4,3]
for i in a :
    print(i, end = " ")
print()

a = input_[2:4,0:5]
for i in a :
    print(*i, end = " ")
print()

a = input_[1:3,1:3]
for i in a :
    print(*i,end = " ")

### none 0s value

In [ ]:
import numpy as np
a = [1,2,0,0,4,0]
a = np.array(a)
b = np.where(a>0)
b = b[0]
print(*b)

### multiple of 3

In [ ]:
import numpy as np
a = np.arange(1,20,2)
print(a)
ind = np.where(a%3 == 0 )
print(*ind[0])

### odd elements 

In [ ]:
import numpy as np
a = np.arange(1,11,1)
c = a%2!=0 
a[c] = -1
print(*a)

#### replace max

In [ ]:
import numpy as np 
a = np.array([11, 2, 13, 4, 15, 6, 27, 8, 19])
b = a.max()
a[a==b] = 0
for i in a :
    print(i)

### negate elements 

In [ ]:
import numpy as np 
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a[2:-2]*=(-1)
for i in a :
    print(i)

### height 

In [ ]:
import numpy as np
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])
indx = np.where(height>155)
# a = age[indx]
# b = height[height>155]
# for i, j in zip(a,b) :
#     print(i,j)  
age=age[indx]
height=height[indx]
# l=len(age)
# for i in range(l):
#     print(age[i],height[i],sep=" ")
for i,j in zip(age,height):
    print(i,j)
    
    

    #### ****-----ALL THE APPROACHS ARE CORRECT ****------

### sort by column

In [ ]:
import numpy as np
li= [[21,20,19,18,17],[16,15,14,13,12],[11,10,9,8,7],[6,5,4,3,2]]
arr_=np.array(li)

for i in range(5):
    arr_[:,i].sort()
print(arr_)   

### killed in USA

In [2]:
import numpy as np 
import csv 

with open("terrorismData.csv",encoding='utf-8') as file_obj :
    file_data = csv.DictReader(file_obj,skipinitialspace = True )
    file_list = list(file_data)

killed = []
country = []

for row in file_list:
    killed.append(row["Killed"])
    country.append(row["Country"])

np_killed = np.array(killed)
np_country = np.array(country)

np_killed[np_killed==""] = "0.0"
np_killed = np.array(np_killed,dtype=float)
np_killed = np.array(np_killed,dtype=int)
bool_arr = np_country == "United States"

val_killed = np_killed[bool_arr]
print(np.sum(val_killed))
# for i in val_killed:
#     print(i)

3771


### total kill in USA

In [3]:
import numpy as np 
import csv 

with open("terrorismData.csv",encoding='utf-8') as file_obj :
    file_list = csv.DictReader(file_obj,skipinitialspace = True )
    killed = []
    country = []

    for row in file_list:
        killed.append(row["Killed"])
        country.append(row["Country"])

    np_killed = np.array(killed)
    np_country = np.array(country)

    np_killed[np_killed==""] = "0.0"
    np_killed = np.array(np_killed,dtype=float)
    np_killed = np.array(np_killed,dtype=int)
    bool_arr = np_country == "United States"

    val_killed = np_killed[bool_arr]
    print(np.sum(val_killed))

3771
